---
# Source: generator/templates/pytorch-job.yaml
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
    name: monitoring
    namespace: mcad-testing
spec:
    priority: 1
    priorityslope: 0.0
    schedulingSpec:
        minAvailable: 1
        requeuing:
            timeInSeconds: 30
    resources:
        Items: []
        GenericItems:
            - replicas: 1
              generictemplate:
                  apiVersion: scheduling.sigs.k8s.io/v1alpha1
                  kind: PodGroup
                  metadata:
                      name: monitoring
                      namespace: mcad-testing
                      labels:
                          appwrapper.mcad.ibm.com: monitoring
                  spec:
                      minMember: 1
            - replicas: 1
              completionstatus: "Complete"
              custompodresources:
                  - replicas: 1
                    requests:
                        cpu: 1
                        nvidia.com/gpu: 0
                        memory: 8Gi
                    limits:
                        cpu: 1
                        nvidia.com/gpu: 0
                        memory: 8Gi
              generictemplate:
                  apiVersion: "kubeflow.org/v1"
                  kind: "PyTorchJob"
                  metadata:
                      name: monitoring
                      namespace: mcad-testing
                      labels:
                          appwrapper.mcad.ibm.com: monitoring
                          pod-group.scheduling.sigs.k8s.io: monitoring
                  spec:
                      pytorchReplicaSpecs:
                          Master:
                              replicas: 1
                              restartPolicy: Never
                              template:
                                  metadata:
                                      namespace: mcad-testing
                                      labels:
                                          appwrapper.mcad.ibm.com: monitoring
                                          pod-group.scheduling.sigs.k8s.io: monitoring
                                  spec:
                                      schedulerName: scheduler-plugins-scheduler
                                      priorityClassName: "low-priority"
                                      terminationGracePeriodSeconds: 1
                                      containers:
                                          - name: pytorch
                                            image: ghcr.io/foundation-model-stack/base:pytorch-latest-nightly-20230212
                                            imagePullPolicy: IfNotPresent
                                            env:
                                                - name: GIT_SSH_COMMAND
                                                  value: "ssh -i /tmp/.ssh/keys/id_rsa -o UserKnownHostsFile=/tmp/.ssh/hosts/known_hosts -vv"
                                            command:
                                                - sh
                                                - -c
                                                - |
                                                  echo "Environment variables set by the kubeflow training operator:"
                                                  echo ${MASTER_ADDR}:${MASTER_PORT}
                                                  echo "PYTHONUNBUFFERED:"${PYTHONUNBUFFERED}
                                                  echo My global rank is ${RANK} / ${WORLD_SIZE}
                                                  echo "Other injected environment variables:"
                                                  echo "NVME_MOUNT_PATH: "${NVME_MOUNT_PATH}
                                                  #
                                                  # User commands
                                                  #
                                                  sleep infinity
                                            resources:
                                                requests:
                                                    cpu: 1
                                                    nvidia.com/gpu: 0
                                                    memory: 8Gi
                                                limits:
                                                    cpu: 1
                                                    nvidia.com/gpu: 0
                                                    memory: 8Gi
                                            volumeMounts:
                                                - name: scratch
                                                  mountPath: /workspace/data
                                                - name: private-ssh-git-deploy-key
                                                  readOnly: true
                                                  mountPath: "/tmp/.ssh/keys"
                                                - name: github-known-hosts
                                                  mountPath: "/tmp/.ssh/hosts"
                                                - name: dshm
                                                  mountPath: "/dev/shm"
                                      volumes:
                                          - name: scratch
                                            persistentVolumeClaim:
                                                claimName: mcad-testing-prod-bucket
                                          - name: private-ssh-git-deploy-key
                                            secret:
                                                secretName: ssh-key-secret
                                                optional: false
                                          - name: github-known-hosts
                                            configMap:
                                                name: ssh-key-configmap
                                          - name: dshm
                                            emptyDir:
                                                medium: Memory
                                      imagePullSecrets: []
